### ISSUE TITLE
Problems while testing locally

### ISSUE THREAD

**Issue by manparvesh** [blindpad/blindpad#10]
Hi,
I cloned the project and after `npm install` and `npm run dev-app`, I was able to run the server on my machine. But when I try to test it by opening it in an incognito window of Chrome, it looks for others for a few seconds and creates a new session because it cannot find any. 
How should I go on with testing it?

**Comment by 0b01** [comment]
Instead of using `/webpack-dev-server `, go to `http://localhost:8080/pad/CeaselessPad2864`

**Comment by manparvesh** [comment]
okay I got it
thanks
