### ISSUE TITLE
Support for other browsers

### ISSUE THREAD

**Issue by manparvesh** [blindpad/blindpad#11]
I think it would be better to add support for Firefox at least, if you are considering this as a long-term project. Since a large number of developers prefer Firefox and this is being developed keeping in mind the developers needs, it should be done as well.
What do you think?

**Comment by 0b01** [comment]
It seems to be working on firefox. Did you encounter a bug?

**Comment by manparvesh** [comment]
Yes, it seems to work fine. I was using `/webpack-dev-server` earlier.
