### ISSUE TITLE
How does blindpad work?

### ISSUE THREAD

**Issue by 0b01** [blindpad/blindpad#12]
Is there any resource on how blindpad works? Can someone give a quick rundown?

Is it through a central server for peer discovery and then all connections are P2P?

**Comment by rmnoon** [comment]
Yep, that's correct.

I never wrote a gigantic design doc but the code is fairly clean and well-commented.

The best place to start is probably here:
https://github.com/blindpad/blindpad/blob/master/src/signaler/Protocol.ts

which explains the messaging protocol between the signaler (the central server that does peer discovery) and then all of the users on a pad.

The next file I'd read is:
https://github.com/blindpad/blindpad/blob/master/src/services/PadModel.ts

Which describes how the state machine gets setup based on messages received from the signaler and how the swarm is built and maintained.

Lastly I'd read:
https://github.com/blindpad/blindpad/blob/master/src/services/UserModel.ts

Which describes how a connection to a peer is maintained and the kinds of information that can flow between peers.

Hope this helps!  Excited that you're thinking of contributing.

**Comment by rmnoon** [comment]
Closing this for now!
