### ISSUE TITLE
Changes to shared pad not showing

### ISSUE THREAD

**Issue by brandonjabr** [blindpad/blindpad#19]
I created a pad using the live demo, then connected to the same pad on a different computer, however I don't see any changes being shared between the two. It asked me to joint the pad, but it just appears blank.

It says 'Looking for others' in the bottom left.

**Comment by rmnoon** [comment]
Unfortunately the signaling server that was powering the hosted version went offline (RedHat changed the business model for OpenShift to eliminate the free tier) so the public version doesn't work now.  It's pretty easy to host on your own, though!
