### ISSUE TITLE
Elm language syntax color

### ISSUE THREAD

**Issue by skitoo** [blindpad/blindpad#4]
Hi

Great job !
Can you add ELM language syntax coloration ? (http://elm-lang.org/)

Thank you :)

**Comment by rmnoon** [comment]
Thanks for opening the first issue! 🎉 

Elm should be on the public site now, too, if you do a hard refresh.  I don't know the language at all (and I'm just using the Codemirror plugin from [here](https://codemirror.net/mode/elm/index.html)) so hopefully it works well!

**Comment by skitoo** [comment]
Thank you! It works :)
